---
title: "dm_bcfs_subject"
author: "Egor Ananyev"
date: '2016-03-03'
output: html_document
---

```{r}
# The list of subjects, the order of conditions, and the thresholds are derived from Subjects.xlsx
# Read in the Excel worksheet:
library(xlsx)
library(ggplot2)
library(plyr)
library(matrixStats)
library(splines)
library(reshape)
source('/Users/Egor/Dropbox/Prog/R/myFunctions/blackTheme.R')
dataDir <- '/Users/Egor/Dropbox/Projects/supr-eff/data_bcfs1/'
subjList <- read.xlsx(file=paste(dataDir,'Subjects.xlsx',sep=''), 1, colIndex=c(1:8), header=T)
subjList$Subj<- as.factor(subjList$Subj)
subjList$Sequence <- as.factor(subjList$Sequence)
condList <- c('cscm','csdm','dscm','dsdm')
# Some additional constants:
nConds <- 6
nc <- nConds-1 # the number of conditions without the blank
shortRT <- .5
outlFac <- 2.5 # outlier factor
# Gathering the directories from the data directory:
allDirs <- dir(dataDir)
# Setting variables for the loop:
ds <- data.frame()
md <- data.frame()
cbound <- data.frame()
curSubj <- 1 #temp
curCond <- 1 #temp
for(curSubj in 1:length(subjList$Subj)){ #going through all dirs
    for(curCond in 1:length(condList)){
        grepPattern <- paste('dm_bcfs-', condList[curCond], '_t0_', subjList$Subj[curSubj], sep='')
        subjDir <- allDirs[grep(grepPattern, allDirs)]
        # With this directory, extracting data:
        subjDataFN <- paste(dataDir, subjDir, '/', subjDir,
                            '_trials.tsv', sep='')
        if(file.exists(subjDataFN)){
            ss <- read.table(subjDataFN, sep='\t', nrows=6, header=T)
            sumss <- ss[,1:29]
            sumss$motPat[sumss$cond=='bcfs-cscm'] <- 'Rotating Target/Rotating Mask'
            sumss$motPat[sumss$cond=='bcfs-dsdm'] <- 'Linear Target/Linear Mask'
            sumss$motPat[sumss$cond=='bcfs-csdm'] <- 'Rotating Target/Linear Mask'
            sumss$motPat[sumss$cond=='bcfs-dscm'] <- 'Linear Target/Rotating Mask'
            # Inserting subject ID
            sumss$SubjID <- subjList$Subj[curSubj]
            sumss$subjThresh <- mean(as.numeric(subjList[curSubj, c('Thresh1', 'Thresh2', 'Thresh3')]), 
                                     na.rm=T)
            # I can't take RT_mean, because it doesn't exclude zeros
            # Need to get the RTs on my own, and since the nTrials might
            # differ...
            nTrials <- ss$n[1]
            rts <- ss[,30:(29+nTrials)]
            rtna <- rts
            rtna[rtna==0] <- NA
            sumss$RTna_mean <- c(rowMeans(rtna[1:nc,],na.rm=T),0)
            sumss$RTna_median <- c(rowMedians(as.matrix(rtna[1:nc,]),na.rm=T),0)
            sumss$RTna_sd <- c(apply(rtna[1:nc,],1,sd,na.rm=T),0)
            sumss$RTna_outlLow <- rowSums(rtna<(sumss$RTna_mean-outlFac*sumss$RTna_sd), na.rm=T)
            sumss$RTna_outlHigh <- rowSums(rtna>(sumss$RTna_mean+outlFac*sumss$RTna_sd), na.rm=T)
            rtna[rtna<(sumss$RTna_mean-outlFac*sumss$RTna_sd)] <- NA
            rtna[rtna>(sumss$RTna_mean+outlFac*sumss$RTna_sd)] <- NA
            sumss$RTna_mean <- c(rowMeans(rtna[1:nc,],na.rm=T),0)
            sumss$RTna_sd <- c(apply(rtna[1:nc,],1,sd,na.rm=T),0)
            sumss$RTna_norm <- c(sumss$RTna_mean[1:nc]/mean(sumss$RTna_mean[1:nc],na.rm=T),0)
            # Binding the summary statistics with the empty data frame
            ds <- rbind(ds, sumss)
            # Gathering RTs:
            cbound <- cbind(sumss,rtna)
            # Renaming the trial columns for easy handling later: 
            trialColNames <- paste('t',as.character(c(1:nTrials)),sep='')
            colnames(cbound)[(length(cbound)-nTrials+1):(length(cbound))] <- trialColNames
            # Melting the data set to have a trial per row:
            melted <- melt(cbound, id=c('SubjID', 'subjThresh', 'motPat', 'maskSpeed','targSpeed'),
                       measure.vars=trialColNames)
            # Renaming the variables for trial and RT:
            melted <- rename(melted,c('variable'='trial','value'='RT'))
            if(curCond==1 & curSubj==1){
                md <- melted
            }else{
                md <- rbind(md, melted)
            }
            print(paste('Processed file',subjDataFN))
        }else{
            print(paste('File does not exist:',subjDataFN))
        }
    }
}
ds$Condition <- as.factor(substr(ds$cond, 6, 9))
ds <- ds[ds$targSpeed>0,]
md <- md[md$targSpeed!=0,] # deleting blank trials
rownames(md)=NULL
```

```{r}
# Line plots of raw RTs per subject
ggplot(ds[ds$Condition=='cscm',], aes(x=maskSpeed, y=RT3_mean, group=SubjID, colour=SubjID)) +  geom_line() + geom_point() + theme_black()
ggplot(ds[ds$Condition=='csdm',], aes(x=maskSpeed, y=RT3_mean, group=SubjID, colour=SubjID)) +  geom_line() + geom_point() + theme_black()
ggplot(ds[ds$Condition=='dscm',], aes(x=maskSpeed, y=RT3_mean, group=SubjID, colour=SubjID)) +  geom_line() + geom_point() + theme_black()
ggplot(ds[ds$Condition=='dsdm',], aes(x=maskSpeed, y=RT3_mean, group=SubjID, colour=SubjID)) +  geom_line() + geom_point() + theme_black()
# Line plots of normalized RTs
ggplot(ds[ds$Condition=='cscm',], aes(x=maskSpeed, y=RT3_norm, group=SubjID, colour=SubjID)) +  geom_line() + geom_point() + theme_black()
ggplot(ds[ds$Condition=='csdm',], aes(x=maskSpeed, y=RT3_norm, group=SubjID, colour=SubjID)) +  geom_line() + geom_point() + theme_black()
ggplot(ds[ds$Condition=='dscm',], aes(x=maskSpeed, y=RT3_norm, group=SubjID, colour=SubjID)) +  geom_line() + geom_point() + theme_black()
ggplot(ds[ds$Condition=='dsdm',], aes(x=maskSpeed, y=RT3_norm, group=SubjID, colour=SubjID)) +  geom_line() + geom_point() + theme_black()
```

```{r, fig.height=4, fig.width=7}
# Creating a data set with summaries per condition
ss = ddply(ds, .(maskSpeed,Condition), summarise, `Mean Normalized RT`=mean(RTna_norm))
ggplot(ss, aes(x=maskSpeed, y=`Mean Normalized RT`, colour=Condition, group=Condition)) +  geom_line() + geom_point() +  theme_black()
```

## Box plots

### Raw
```{r, fig.height=3, fig.width=5}
ggplot(ds, aes(x=factor(maskSpeed), y=RTna_mean, colour=motPat)) +  geom_boxplot() + 
    labs(x='Mask Speed', colour='Motion Pattern', y='Mean RT') + theme_black()
```

### Normalized
```{r, fig.height=3, fig.width=5}
ggplot(ds, aes(x=factor(maskSpeed), y=RTna_norm, colour=motPat)) +  geom_boxplot() + 
    labs(x='Mask Speed', colour='Motion Pattern', y='Normalized RT') + theme_black()
```

## Smoothed on raw

### Quadratic effects
```{r, fig.height=3, fig.width=5}
ggplot(md, aes(x=maskSpeed, y=RT, colour=motPat, group=motPat)) +  
    stat_smooth(method='lm', formula=y~ns(x,2)) +
    labs(x='Mask Speed', y='RT', colour='Motion Pattern') + theme_black()
```

### Cubic effects
```{r, fig.height=3, fig.width=5}
ggplot(md, aes(x=maskSpeed, y=RT, colour=motPat, group=motPat)) +  
    stat_smooth(method='lm', formula=y~ns(x,3)) +
    labs(x='Mask Speed', y='RT', colour='Motion Pattern') + theme_black()
```

### Quartic effects
```{r, fig.height=3, fig.width=5}
ggplot(md, aes(x=maskSpeed, y=RT, colour=motPat, group=motPat)) +  
    stat_smooth(method='lm', formula=y~ns(x,4)) +
    labs(x='Mask Speed', y='RT', colour='Motion Pattern') + theme_black()
```

## Smoothed on normalized

### Normalized data set
```{r}
# Compiling a data set containing two normalized values
# Normalizing by subject
mds <- ddply(md, .(SubjID), summarise, subjMean=mean(RT, na.rm=T))
mdn <- merge(md,mds,by='SubjID')
# Normalizing by motion pattern
mdc <- ddply(md, .(SubjID, motPat), summarise, condMean=mean(RT, na.rm=T))
mdn <- merge(mdn,mdc,by=c('SubjID','motPat'))
# Computing the normalized RTs
mdn$subjNormRT <- mdn$RT / mdn$subjMean
mdn$condNormRT <- mdn$RT/mdn$condMean
```

### Cubic effects
```{r, fig.height=3, fig.width=5}
ggplot(mdn, aes(x=maskSpeed, y=subjNormRT, colour=motPat, group=motPat)) +  
    stat_smooth(method='lm', formula=y~ns(x,3)) + 
    geom_point(data=ds, aes(x=maskSpeed, y=RTna_norm, colour=motPat), 
               position=position_dodge(width=.4), size=.3, shape=1) +
    labs(x='Mask Speed', y='RT Normalized by Subject', colour='Motion Pattern') + 
    scale_x_continuous(breaks=unique(mdn$maskSpeed)) + theme_black()
ggplot(mdn, aes(x=maskSpeed, y=subjNormRT, colour=motPat, group=motPat)) +  
    stat_smooth(method='lm', formula=y~ns(x,3)) + 
    geom_point(data=ds, aes(x=maskSpeed, y=RTna_norm, colour=motPat), 
               position=position_dodge(width=.4), size=.9) + # square is shape=7
    labs(x='Mask Speed', y='RT Normalized by Subject', colour='Motion Pattern') + 
    scale_x_continuous(breaks=unique(mdn$maskSpeed)) + theme_bw()
```

